### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by Sheldon-NULL** [fudiwei/DotNetCore.SKIT.FlurlHttpClient#12]
https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient/blob/main/docs/Cookbook_HttpClientFactory.md

本来想拉下来自己改得，没找到这个文件

![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient/assets/83170675/400cc968-ad6f-426d-8827-eb210e72aff3)

是CreateClient()，不是.Create()

**Comment by fudiwei** [comment]
已更正，感谢反馈。
