### ISSUE TITLE
验证回调通知事件签名提示：Signature does not match

### ISSUE THREAD

**Issue by Lingweiy** [fudiwei/DotNetCore.SKIT.FlurlHttpClient#13]
想问下调用VerifyEventSignatureAsync提示（Signature does not match）是什么原因？
Signature does not match. Maybe "JrJT0uT4TKpnqka6mLemixE2Gy5JShpkctrX7gfjiVYCvHAvze3dVIvaTcU/e2tQ1Ises/2w4qsbmG6huw4L5fmz/XqvboxGNNj92z3Y2JgyC4LcZzUtvpiaRObwr8vF6cd53IGrCRg0OOgFC8BtgxgvNGjtFyEOc4cakkj7xDOe2MMue7hP35x1+ZEyWOp2TyiqlQPeZScoMaXDsNEBCjaGRsiRGCVNnR6UDx417kuH3G09601mtBozMte9+t97mBYCSOoNOoXC3pZvfFclzZgibCX3hZs8kJSFcNoJ+3K/nbrnivgOj3ddzo8Np35yYgIj3Pvpjg4WdHQLApcprA==" is an illegal signature.
使用的就是请求头微信返回的签名字段（Wechatpay-Signature），ExecuteQueryCertificatesAsync拿到的平台证书我也调用（DecryptResponseSensitiveProperty）解密了
CertificateEntry里的AlgorithmType是“RSA”，是否应该是“WECHATPAY2-SHA256-RSA2048”是这个原因吗？
PS.我将AlgorithmType改为“AlgorithmType”，会提示我：The value of `algorithmType` an invalid value. (Parameter 'algorithmType')
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient/assets/48813545/fc98fc3c-29d4-4a01-ab34-0f26fb2d89ef)

**Comment by fudiwei** [comment]
字面意思，签名错误。

可能传参错误、混用了不同商户号（即用商户A去验签商户B的回调）等原因。

请贴下完整代码看看。

**Comment by Lingweiy** [comment]
目前还没支持多商户号，只配置了一个商户号，应该不是混用的原因。
这是Controller:
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient/assets/48813545/39755162-1e17-4a1b-aa02-cf3ad1741ec8)
这是service：
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient/assets/48813545/a4e72dc9-6b97-439d-a2b8-77386223728f)
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient/assets/48813545/9afd33ae-a95a-4e1b-9189-33cf46c272d5)
后面的 DecryptEventResource 方法是可以解密出来数据的

**Comment by fudiwei** [comment]
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient/assets/18504146/3de88f10-7287-4658-bcce-4a08d15f5248)

你应该使用收到的原始数据验签，而不是先反序列化后再序列化回 JSON 字符串 —— 你无法保证你序列化出来的结果跟你收到的是一模一样的。

**Comment by Lingweiy** [comment]
原来是这样，感谢大神指点！
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient/assets/48813545/2b82bb0a-3dd9-442a-be59-df8bdd2870de)

因为一直读不到Request.Body,用 Sample 里读取body的方式也不行,最后无奈选择了这种方式...我再研究下
