### ISSUE TITLE
为啥不整合一下支付宝的SDK

### ISSUE THREAD

**Issue by haifding** [fudiwei/DotNetCore.SKIT.FlurlHttpClient#7]
为啥不整合一下支付宝的SDK

**Comment by fudiwei** [comment]
感谢关注。

支付宝已经有官方 SDK 了。

**Comment by xpnew** [comment]
支付宝的SDK用着不方便，大佬不如干脆一起弄了算了。

**Comment by hezlog** [comment]
跪求大佬整合一下支付宝SDK。

**Comment by hezlog** [comment]
大佬的代码让我等恍然大悟，居然可以用扩展方法来写API接口，这是我之前没见过的。

**Comment by hezlog** [comment]
另外就是一点小问题，就是目录名能不能缩短一点点，打开工程时报路径超过 260字符。
