### ISSUE TITLE
缺少 SKIT.FlurlHttpClient.Tools.CodeAnalyzer 包，辛苦作者大佬上传一下nuget

### ISSUE THREAD

**Issue by hezlog** [fudiwei/DotNetCore.SKIT.FlurlHttpClient#8]
编译单元测试项目时 缺少 SKIT.FlurlHttpClient.Tools.CodeAnalyzer 包，辛苦作者大佬上传一下nuget。
编译环境：VS2019，NET472

**Comment by fudiwei** [comment]
没有缺少，是 Visual Studio 本身与 .NET CLI 集成的 Bug。

请使用终端进入项目根目录，执行 `dotnet restore`，然后重启 Visual Studio 即可。

**Comment by hezlog** [comment]
按大佬说的恢复一下果然正常了。
